feria_app/urls.py
from django.urls import path
from .views import ProductoListView,ProductoCreateView , ProductoDeleteView , ProductoUpdateView , ProductoDetailView

from .router import router

app_name = "productos"

urlpatterns = [
    path("", ProductoListView.as_view(), name= "all"),
    path("create/", ProductoCreateView.as_view(), name= "create"),
    path("<int:pk>/detail/", ProductoDetailView.as_view(), name= "detail"),
    path("<int:pk>/update/", ProductoUpdateView.as_view(), name= "update"),
    path("<int:pk>/delete/", ProductoDeleteView.as_view(), name= "delete"),
]

urlpatterns += router.urls

feria_franca_empedrado/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from .views import Landing, Contacto, Productos, Registrarse, SobreNosotros, Tienda, Crud

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Landing.as_view(), name="landing"),
    path('contacto/', Contacto.as_view(), name="contacto"),
    path('productos/', Productos.as_view(), name="productos"),
    path('registrarse/', Registrarse.as_view(), name="registrarse"),
    path('sobrenosotros/', SobreNosotros.as_view(), name="sobre_nosotros"),
    path('tienda/', Tienda.as_view(), name="tienda"),
    path('crud/', Crud.as_view(), name="crud"),
    path('productos_app/', include("feria_app.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

feria_app/models.py
from typing import Any
from django.db import models

# Create your models here.
class Producto(models.Model):
    cod         = models.CharField(max_length=6)
    articulo    = models.CharField(max_length=100)
    descripcion = models.CharField(max_length=50)
    precio      = models.FloatField(blank=True, null=True)
    img         = models.CharField(max_length=100)

    class Meta:
        db_table = "productos_tabla"  

    def __str__(self):
        return f"El articulo {self.articulo} sale {self.precio}"
    
    def get_fields(self):
        return[
            (field.verbose_name, field.value_from_object(self))
            for field in self.__class__._meta.fields[1:]
        ]

feria_app/views.py
from django.shortcuts import render
from django.urls import reverse_lazy

from .models import Producto

from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

# Create your views here.

class ProductoBaseView():
    template_name = "productos_app.html"
    model = Producto
    fields = "__all__"
    success_url = reverse_lazy("productos:all")

class ProductoListView(ProductoBaseView, ListView):

    """
    Muestra todos los productos!!!
    """

class ProductoDetailView(ProductoBaseView, DetailView):

    template_name = "productos_detail.html"

class ProductoCreateView(ProductoBaseView, CreateView):

    template_name = "productos_create.html"
    extra_context = {
        "tipo" : "Crear Producto"
    }


class ProductoUpdateView(ProductoBaseView, UpdateView):

    template_name = "productos_create.html"
    extra_context = {
        "tipo" : "Actualizar Producto"
    }

    
class ProductoDeleteView(ProductoBaseView, DeleteView):

    template_name = "productos_delete.html"
    extra_context = {
        "tipo" : "Borrar Producto"
    }
    success_url = reverse_lazy("productos:all")

feria_franca_empedrado/views.py
from django.views.generic import TemplateView

class Landing(TemplateView):
    template_name = "pantallas/landing_page.html"

class Contacto(TemplateView):
    template_name = "pantallas/contacto.html"

class Productos(TemplateView):
    template_name = "pantallas/productos.html"

class Registrarse(TemplateView):
    template_name = "pantallas/registrarse.html"

class SobreNosotros(TemplateView):
    template_name = "pantallas/sobrenosotros.html"

class Tienda(TemplateView):
    template_name = "pantallas/tienda.html"

class Crud(TemplateView):
    template_name = "pantallas/crud.html"

feria_app/templates/productos_app.html
{% extends 'base.html' %}

{% block content %}

<main>
    <div class="main-color-productos">
        <h3>Todos los productos</h1>
        <h2><a href="{% url 'productos:create' %}">Cargar Producto</a></h2>
        {% for producto in producto_list %}
        <div class="list">
            <span>
                <p>{{producto.articulo}}</p>
            </span>
            <span>
                <label for="">Detalle: </label>
                <a href="{% url 'productos:detail' producto.id %}">+</a>
            </span>
            <span>
                <label for="">Editar: </label>
                <a href="{% url 'productos:update' producto.id %}">+</a>
            </span>
            <span>
                <label for="">Borrar: </label>
                <a href="{% url 'productos:delete' producto.id %}">+</a>
            </span>
        </div>

        {% endfor %}
    </div>
</main>
{% endblock %}

feria_app/templates/productos_create.html
{% extends 'base.html' %}
{% block content %}

<main>
    <div class="main-color-productos">
        <h2>Cargando producto</h2>
        <form method="post">
            {% csrf_token %}
            <div>{{form.as_p}}</div>
            <br>
            <input type="submit" value="{{ tipo }}"/>
        </form>

        <a href="{% url 'productos:all' %}">Volvamos al Inicio</a>
    </div>
</main>
{% endblock %}

feria_app/templates/productos_delete.html
{% extends 'base.html' %}
{% block content %}

<main>
    <div class="main-color-productos">
        <h2>BORRAR PRODUCTO</h2>
        <form method="post">
            {% csrf_token %}
            <p>¿Estás seguro de que deseas borrar este producto?</p>
            <div>{{ producto.articulo }}</div>
            <input type="submit" value="Borrar Producto" />
        </form>

        <a href="{% url 'productos:all' %}">Volvamos al Inicio</a>
    </div>
</main> 
{% endblock %}

feria_app/templates/productos_detail.html
{% extends 'base.html' %}
{% block content %}

<main>
    <div class="main-color-productos">
        <h2>{{producto.articulo}}</h2>
        {% for label, value in producto.get_fields %}

        <p>{{label | upper}}</p>
        <p>{{value}}</p>

        {% endfor %}

        <a href="{% url 'productos:all' %}">BACK</a>
    </div>
</main> 
{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://kit.fontawesome.com/b509d92839.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/registrarse.css'  %}">
    <link rel="stylesheet" href="{% static 'css/tienda.css'  %}">
    <link rel="stylesheet" href="{% static 'css/productos.css'  %}">
    <link rel="stylesheet" href="{% static 'css/style.css'  %}">
    <title>Feria Empedrado</title>
</head>
<header>
    <div class="imgEncabezado" style="background-image: url('{% static 'imagenes/imagen1.jpg' %}')">
        <h1>Feria Franca Empedrado</h1>
    </div>
    <nav id="navBarId">
        <div>
            <input type="checkbox">
            <i class="fas fa-bars"></i>
            <i class="fas fa-times"></i>
                <nav>
                    <ul>
                        <li><a href="{% url 'landing' %}">Inicio </a></li>
                        <li><a href="{% url 'productos' %}">Productos</a></li>
                        <li><a href="{% url 'tienda' %}">Tienda</a></li>
                        <li><a href="{% url 'registrarse' %}">Registrarse</a></li>
                        <li><a href="{% url 'contacto' %}">Contacto</a></li>
                        <li><a href="{% url 'sobre_nosotros' %}">Sobre nosotros</a></li>
                        <li><a href="{% url 'productos:all' %}">CRUD</a></li>
                    </ul>
                </nav>
        </div>
    
    </nav> 
</header>   

{% block content %}
{% endblock %}

<footer>
    <br>
        <div>
            <a href="http://www.twitter.com" target="_blank"><i class="fa fa-twitter" aria-hidden=true></i></a>
            <a href="http://www.facebook.com/bernardo.javier.garcia" target="_blank"><i class="fa fa-facebook" aria-hidden=true></i></a>
            <a href="http://www.pinterest.com" target="_blank"><i class="fa fa-pinterest" aria-hidden=true></i></a>
            <a href="http://www.instagram.com/bjavierg/" target="_blank"><i class="fa fa-instagram" aria-hidden=true></i></a>
            <a href="https://www.linkedin.com/in/bernardo-javier-garcia-75ba9925a/" target="_blank"><i class="fa fa-linkedin" aria-hidden=true></i></a>
        </div>
        <br>
        <p><b>Derechos reservados @2023</b></p>
</footer>
<script type="module" src="{% static 'script/carrito.js'  %}"></script>
</html>

templates/pantallas/contacto.html
{% extends 'base.html' %}

{% block content %}
<main>
    <h2>Contactos</h2> 
    <p></p> <b>En donde nos encuentras</b> ✅</p>
    <div class="comentario">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d882.0243019375627!2d-58.76737576371814!3d-27.837546982097223!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x944f8bc766bcc815%3A0xe98a6554344edb2b!2sAutomec!5e0!3m2!1ses-419!2sar!4v1684274808934!5m2!1ses-419!2sar" width="300" height="225" style="border: 1px;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>

        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3524.3005892073097!2d-58.811741324617934!3d-27.954079137517823!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x944f93923558bdaf%3A0xcb796337e3d4445b!2sPlaza%2025%20de%20Mayo!5e0!3m2!1ses-419!2sar!4v1684274252435!5m2!1ses-419!2sar" width="300" height="225" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"align="left"></iframe>
    </div>
    <br>
    <hr>
    <h3>Contacto</h3>
    <hr>
    <p>Domicilio de comercializacion en <b>Empedrado</b>: Plaza 25 de Mayo </p>
    <p>Domicilio de comercializacion y elaboracion: <b>Ruta 12 km 989,5 Manuel Derqui</b></p>
    <p>Productor: <b>Castagna Jorge</b></p>
</main>

{% endblock %}

templates/pantallas/crud.html
{% extends 'base.html' %}
{% load static %}
{% block content %}



{% endblock %}

templates/pantallas/landing_page.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<main>
    <div class="contenedor_con_sidebar">
        <aside  class="sidebar">
            <b>¡Bienvenidos a la Feria Franca de Empedrado!</b>

            En nuestra hermosa ciudad de <b>Empedrado</b>, Corrientes,
            nos enorgullece presentar nuestra Feria Franca, un espacio donde se celebra la producción local y se fomenta el consumo de alimentos frescos y saludables. 
            Nos dedicamos principalmente a la producción de frutas, hortalizas y verduras orgánicas,
            así como a la elaboración artesanal de dulces caseros que deleitan los paladares más exigentes.
        </aside>
        <div  class="cuerpo-principal">
            <img class="foto_portada" src="{% static '/imagenes/Stan de dulces.jpg' %}" alt="feria empedrado" width="80%">
        </div>    
        <aside  class="sidebar">
            En la Feria Franca de Empedrado, no solo encontrarás productos deliciosos,
            también vivirás una experiencia única. 
            Nuestro objetivo es promover el comercio justo, 
            fortalecer los lazos entre los productores y los consumidores, 
            y generar un sentido de comunidad en torno a la producción local. 
            Ven a visitarnos y descubre la frescura,
            la calidad y la calidez de nuestros productos y de las personas que los hacen posibles.
        </aside>     
    </div>    
</main>

{% endblock %}

templates/pantallas/productos.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main>
      <br>
      <h2>Productos de la Feria</h2>

   

  
      </nav> 
    </header>
  
    <main>

      <div id="conteItemscarrousel">
        
        <div class="itemCarrousel" id="itemCarrousel-1"> 
          <div class="tarjetaCarrousel" id="tarjetaCarrousel-1">
            <img src="{% static '/imagenes/Stan de dulces.jpg' %}" alt="item-1-carrousel">
          </div>
          <div class="flechasCarrousel">
              <a href="#itemCarrousel-3">
                <i class="fa-solid fa-arrow-left"></i></a>
              <a href="#itemCarrousel-2">
                <i class="fa-sharp fa-solid fa-arrow-right"></i>
              </a>
          </div> 
        </div>
          
        <div class="itemCarrousel" id="itemCarrousel-2"> 
            <div class="tarjetaCarrousel" id="tarjetaCarrousel-2">
                <img src="{% static '/imagenes/zapallitos.jpg' %}" alt="item-2-carrousel"> 
            </div>
            <div class="flechasCarrousel">
                <a href="#itemCarrousel-1">
                  <i class="fa-solid fa-arrow-left"></i></a>
                <a href="#itemCarrousel-3">
                  <i class="fa-sharp fa-solid fa-arrow-right"></i>
                </a>
            </div>
        </div> 

        <div class="itemCarrousel" id="itemCarrousel-3"> 
            <div class="tarjetaCarrousel" id="tarjetaCarrousel-3">
                <img src="{% static '/imagenes/bondiola.jpg' %}" alt="item-3-carrousel">
            </div>
            <div class="flechasCarrousel">
                <a href="#itemCarrousel-2">
                  <i class="fa-solid fa-arrow-left"></i></a>
                <a href="#itemCarrousel-1">
                  <i class="fa-sharp fa-solid fa-arrow-right"></i></a>
            </div>  
        </div><br><br>
      </div> 
      <h3 > <p align="center" style="color:black">Estos son algunos de nuestros productos naturales, sin contaminantes, de produccion propia, que comercializamos en la Feria de Empedrado. </p>   </h3>
      
    </main>  
        
    {% endblock %}

templates/pantallas/registrarse.html
{% extends 'base.html' %}

{% block content %}
<main>
  <br>  
    <section class="formulario">
        <h2>Formulario de registro</h2>
        <form>
            <label for="firstname">Nombre:</label> <input type="text" name="firstname" placeholder="Ingrese su nombre aqui..."required><br><br>
            <label for="lastname">Apellido:</label> <input type="text" name="lastname" placeholder="Ingrese su apellido aqui..."required><br><br>
            <label for="email">e-mail:</label> <input type="email" name="email" placeholder="Ingrese su email"required><br><br>
            <label for="street">Direccion:</label> <input type="text" name="street" placeholder="Ingrese su calle aqui..."required><br><br>
            <label for="city">Ciudad:</label> <input type="text" name="city" placeholder="Ingrese ciudad aqui..."required><br><br>
            <label for="zipcode">Codigo postal:</label> <input type="text" name="zipcode" placeholder="Ingrese codigo postal..."required><br><br>
            <label for="birthDate">Fecha de nacimiento (dd/mm/yyyy):</label> <input type="date" name="birthDate" placeholder="dd/mm/yyyy"required><br><br>
            
            <p>
                Genero:
                <input type="radio" name="gender" value="Hombre" checked>Hombre
                <input type="radio" name="gender" value="Mujer">Mujer
                <input type="radio" name="gender" value="Otro">Otro
            </p>
            <p>
                Estudios:
                <input type="checkbox" name="estudio" value="primario" display="block">Primarios
                <input type="checkbox" name="estudio" value="secundario">Secundarios
                <input type="checkbox" name="estudio" value="terciario">Terciarios
                <input type="checkbox" name="estudio" value="universitario">Universitarios
                <input type="checkbox" name="estudio" value="otro">Otro
            </p>
            <input type="submit"value="Enviar">
        </form>

        
    </section>
</main>  

{% endblock %}

templates/pantallas/sobrenosotros.html
{% extends 'base.html' %}
{%  load static %}
{% block content %}
<main>
    
    <div class="comentario">
        <h3 align="center" >La Feria Franca</h3>
        <p>La feria Franca esta constituida por productores de la Agricultura Familiar 
            que comercializan en forma directa los productos cultivados y elaborados por ellos 
            mismos en forma directa al consumidor, 
            garantizando de esta forma la calidad de sus mercaderias y cuyo objeto es la 
            autosustentacion familiar de los productores como el menor costo de sus productos 
            ofrecidos a los consumidores.
        
            Te invitamos a explorar nuestra página y descubrir más sobre la Feria Franca de Empedrado. 
            Únete a nosotros en este movimiento hacia una alimentación más saludable, 
            sostenible y deliciosa. 
            <b>¡Te esperamos con los brazos abiertos!</b>
        </p>
        
        <img src="{% static '/imagenes/IMG-20180428-WA0003.jpg' %}" alt="" width="60%" height="80%" style="border-radius: 20px;" >
    </div>
</main>  

{% endblock %}

templates/pantallas/tienda.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<main>
    <br>
    <h2>Productos de la Feria</h2>
    <p><b>Ofertas del dia:</b> haga su consulta mediante nuestras lineas de contacto</p>
    
    <div id="grid-container"></div>

</main>

{% endblock %}